### ISSUE TITLE
can't download the ppt or pdf?

### ISSUE THREAD

**Issue by wdongm** [sanketh95/coursera-offline#1]
First i want to say it's fantastic job,most of the other program can't work again,and it save a lot of time , thank you ,but i find that it can't download the ppt or pdf.

**Comment by sanketh95** [comment]
Thanks for bringing it up. I did it initially only for videos. I'll be sure to extend the support for other course materials as well

**Comment by sanketh95** [comment]
@wangdongming007  It can now download ppts and pdfs. Post here for any issues. Sorry for the delay.
Cheers
