### ISSUE TITLE
Coursera platform change, script no more operational 

### ISSUE THREAD

**Issue by Sim4n6** [sanketh95/coursera-offline#6]
Since there has been a coursera platform change, and the old platform is stopped since June 2016, in other words, the script is not downloading any videos any more. please check this [link](https://learner.coursera.help/hc/en-us/articles/209818623)

Furthermore, when the script fetch "course video page"  it get the following html page (part of it) 

> This page is no longer available.This page was hosted on our old technology platform. We\'ve moved to our new platform at <a href="https://www.coursera.org/">www.coursera.org</a>. Explore our <a href="https://www.coursera.org/browse">catalog</a> to see if this course is available on our new platform, or learn more about the platform transition <a href="https://learner.coursera.help/hc/en-us/articles/209818623">here</a>.

please let's try update this awesome script together :+1:

**Comment by OSryx** [comment]
There is a value in the link **CLASS_VIDEO_URL_TEMPLATE** that is no more valid.

the new value contain a _9BqZe_ I don"t know how to compute it: 
for instance : 
https://www.coursera.org/learn/learning-how-to-learn/lecture/_9BqZe_/summary-video-for-module-1
